name: "lygem-dev"
services:
  dev:
    volumes:
      - type: bind
        source: ..
        target: /workspace
      - type: volume
        source: npm-global
        target: /home/node/.npm-global
      - type: volume
        source: npm-cache
        target: /home/node/.npm
      - type: volume
        source: cache
        target: /home/node/.cache
      - type: volume
        source: node-modules-root
        target: /workspace/node_modules
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    environment:
      NPM_CONFIG_PREFIX: /home/node/.npm-global
    tty: true

volumes:
  npm-global:
  npm-cache:
  node-modules-root:
  cache:
